#!/bin/bash

# Author: Henry Schuler
# Copyright 2021, Henry Schuler, All rights reserved.

startSpeedtest() {
networkLocation=$1

speed=$(speedtest)

hostName=$(echo $speed | sed -n -e "s/\(.*Hosted by \)\(.*\)\( (.*\)/\2/gp")
hostLocation=$(echo $speed | sed -n -e "s/\(.*Hosted by.*(\)\(.*\)\().*\)/\2/gp")
hostDistance=$(echo $speed | sed -n -e "s/\(.*Hosted by.*\[\)\([0-9]*.[0-9]*\)\( km\].*\)/\2/gp")
hostPing=$(echo $speed | sed -n -e "s/\(.*Hosted by.*\]: \)\([0-9]*.[0-9]*\)\( ms.*\)/\2/gp")
download=$(echo $speed | sed -n -e "s/\(.*Download: \)\([0-9]*.[0-9]*\)\(.*U.*\)/\2/gp")
upload=$(echo $speed | sed -n -e "s/\(.*Upload: \)\([0-9]*.[0-9]*\)\(.*\)/\2/gp")

mysql -uinternet -pinternet << MY_QUERY
CREATE DATABASE IF NOT EXISTS InternetDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE InternetDB;
CREATE TABLE IF NOT EXISTS Speedtest (ScanId INT(11) NOT NULL auto_increment, Date DATETIME NOT NULL, Download FLOAT(7,3) DEFAULT NULL, Upload FLOAT(7,3) DEFAULT NULL, NetworkLocation VARCHAR(30) DEFAULT NULL, HostName VARCHAR(30) DEFAULT NULL, HostLocation VARCHAR(20) DEFAULT NULL, HostDistance FLOAT(7,3) DEFAULT NULL, HostPing FLOAT(9,3) DEFAULT NULL, primary key (ScanId));
INSERT INTO Speedtest (Date, Download, Upload, NetworkLocation, HostName, HostLocation, HostDistance, HostPing) VALUES (now(), $download, $upload, "$networkLocation", "$hostName", "$hostLocation", $hostDistance, $hostPing);
MY_QUERY
}

while getopts ?hl: opts
do
        case $opts in
                \?|h)
                        echo "Help page:"
                        echo "-h        HELP"
                        echo "-l LocationID     1 = Zerlaut-Kluftern"
                        echo "                  2 = DHBW-Friedrichshafen"
                        echo "                  3 = Isny-Kastellstraße"
			;;
                l)
                        case $OPTARG in
				1)
					startSpeedtest "Zerlaut-Kluftern"
					;;
				2)
					startSpeedtest "DHBW-Friedrichshafen"
					;;
				3)
					startSpeedtest "Isny-Kastellstraße"
					;;
                        esac
                        ;;
        esac
done

